### ISSUE TITLE
Broken links to discipline specific requirements

### ISSUE THREAD

**Issue by doigl** [rdmorganiser/rdmo-catalog#99]
The first three links to the examples for discipline specific requirments in the section General - Other Requirements I are broken.

The english version of this section looks nicer.

The right links could be:

Guidelines on the Handling of Research Data in Biodiversity Research: https://www.dfg.de/download/pdf/foerderung/grundlagen_dfg_foerderung/forschungsdaten/guidelines_biodiversity_research.pdf

Bereitstellung und Nutzung quantitativer Daten in der Bildungsforschung: https://www.dfg.de/download/pdf/foerderung/grundlagen_dfg_foerderung/informationen_fachwissenschaften/geisteswissenschaften/forschungsdaten_memorandum_fk_109.pdf

Förderkriterien für wissenschaftliche Editionen in der Literaturwissenschaft:
https://www.dfg.de/download/pdf/foerderung/grundlagen_dfg_foerderung/informationen_fachwissenschaften/geisteswissenschaften/foerderkriterien_editionen_literaturwissenschaft.pdf

**Comment by Zack-83** [comment]
Since (1) the DFG has the bad habit of changing continuously the addresses of its regulative documents and (2) there are more than three disciplines, I suggest to replace the subject-specific links with their parent page:

* [DE] [Fachspezifische Empfehlungen zum Umgang mit Forschungsdaten](https://www.dfg.de/foerderung/grundlagen_rahmenbedingungen/forschungsdaten/empfehlungen/index.html)
* [EN] [Subject-specific Recommendations on the Handling of Research Data](https://www.dfg.de/en/research_funding/principles_dfg_funding/research_data/recommendations/index.html)

@jmfrenzel @doigl @torsten-rathmann Could it be a feasible solution?
